install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
- sudo dpkg -i hugo*.tar.gz
- hugo version
before_script:
- rm -rf public
script:
- hugo
branches:
 only:
 - master